Feature connection
s-hayashi1104/tpa-03-mystore pull request #1
Opened 2018-11-13 11:38 UTC by s-hayashi1104

途中経過です、レスポンスがかえって来ないです

2018-11-13 11:49 UTC, clonable-eden requested changes
@s-hayashi1104 コメントしました

2018-11-13 11:49 UTC, clonable-eden commented on server/setup.js
> +    const connection = db.connect();
asynchronousな関数を使っているので、ここはawaitしなければなりません

2018-11-13 11:49 UTC, clonable-eden commented on server/setup.js
> +  app.get('/api/items', (req, res) => {
app.get('/api/items', async (req, res) => {

2018-11-13 11:49 UTC, clonable-eden commented on server/setup.js
> +    connection.query('select id, name, price, image_url from ‘items’;',
せっかくのmysql2/promiseなので、ここはawaitしてあげたほうがいいです

2018-11-13 14:19 UTC, clonable-eden requested changes

2018-11-13 14:19 UTC, clonable-eden commented on server/setup.js
> +    const connection = await db.getConnection;
getConnectionはfunctionなので
```javascript
const connection = await db.getConnection();
```

2018-11-13 14:21 UTC, clonable-eden commented on server/setup.js
> +    connection.query('select id, name, price, image_url from ‘items’;',
参考
https://github.com/sidorares/node-mysql2#using-promise-wrapper

2018-11-13 14:39 UTC, clonable-eden commented on server/setup.js
> +    connection.query('select id, name, price, image_url from ‘items’;',
あとちなみにクエリもおかしい
テーブル名のところは変なクォートは要らない
もしやりたいならバッククォートにすべし

2018-11-13 17:00 UTC, clonable-eden reviewed
@s-hayashi1104 追加コメントしました

2018-11-13 17:00 UTC, clonable-eden commented on server/setup.js
> +    const [row, field] = await connection.query('select `id`, `name`, `price`, `image_url` from `items`');
バッククォートをつけるとものすごい違和感あるなぁ。。。
個人的には外した方が読みやすいかなーと思った。

2018-11-13 17:00 UTC, clonable-eden commented on server/setup.js
> +    });
async/awaitを使うときはtry catchでくくるクセを付けたほうがいい。もちろんすべての箇所で必要なわけではないが、インタフェース境界では必要。
今回の場合、
```javascript
app.get('/api/items', async(req, res) => {
  try {
    const connection = db.getConnection();
    // ...
    res.json({
      row,
      field
    });
  } catch (err) {
    console.error(err);
    res.status(500);
  }
});
```
業務では https://expressjs.com/ja/guide/error-handling.html こんなこともしたりする（今回はやらなくてよい、ひとまず）

2018-11-14 11:58 UTC, Mitsuru53 commented on server/db/connection.js
>      const connection = await mysql.createConnection({
connectionという変数で受けなくても、そのままreturnしちゃっていいと思います
return await mysql....

2018-11-14 12:32 UTC, merged